### ISSUE TITLE
As soon as I imported this library into my project, webpack crashed.

### ISSUE THREAD

**Issue by gwenf** [mikenikles/html-to-react#41]
I didn't start using the library yet. I just included it like this: 
`import HtmlToReact from 'html-to-react'`

Here is the error I am getting in terminal:

```javascript
/Users/gwen/Desktop/preferably6/node_modules/webpack-core/lib/NormalModuleMixin.js:151
				throw e;
				^
Error: ./~/ent/reversed.json
Module parse failed: /Users/gwen/Desktop/preferably6/node_modules/ent/reversed.json Unexpected token (2:7)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:7)
    at Parser.pp.raise (/Users/gwen/Desktop/preferably6/node_modules/acorn/dist/acorn.js:920:13)
    at Parser.pp.unexpected (/Users/gwen/Desktop/preferably6/node_modules/acorn/dist/acorn.js:1483:8)
    at Parser.pp.semicolon (/Users/gwen/Desktop/preferably6/node_modules/acorn/dist/acorn.js:1462:73)
    at Parser.pp.parseExpressionStatement (/Users/gwen/Desktop/preferably6/node_modules/acorn/dist/acorn.js:1976:8)
    at Parser.pp.parseStatement (/Users/gwen/Desktop/preferably6/node_modules/acorn/dist/acorn.js:1754:188)
    at Parser.pp.parseBlock (/Users/gwen/Desktop/preferably6/node_modules/acorn/dist/acorn.js:1991:21)
    at Parser.pp.parseStatement (/Users/gwen/Desktop/preferably6/node_modules/acorn/dist/acorn.js:1735:19)
    at Parser.pp.parseTopLevel (/Users/gwen/Desktop/preferably6/node_modules/acorn/dist/acorn.js:1648:21)
    at Parser.parse (/Users/gwen/Desktop/preferably6/node_modules/acorn/dist/acorn.js:1616:17)
    at Object.parse (/Users/gwen/Desktop/preferably6/node_modules/acorn/dist/acorn.js:882:44)
 @ ./~/ent/encode.js 2:18-44./~/ent/entities.json
Module parse failed: /Users/gwen/Desktop/preferably6/node_modules/ent/entities.json Unexpected token (2:13)
You may need an appropriate loader to handle this file type.
```

And my package.json:

```javascript
{
  "name": "gwen",
  "version": "0.0.1",
  "description": "Marketing App",
  "main": "index.js",
  "scripts": {
    "test": "karma start",
    "start": "gulp"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "core-js": "^2.4.1",
    "dns": "^0.2.2",
    "dropzone": "^4.3.0",
    "extract-text-webpack-plugin": "^1.0.1",
    "file-loader": "^0.8.5",
    "font-awesome": "^4.6.1",
    "font-awesome-webpack": "0.0.4",
    "fontawesome": "^4.5.0",
    "fs": "0.0.2",
    "fs-extra": "^0.30.0",
    "history": "^2.0.1",
    "html-to-react": "^1.0.0",
    "jquery": "^2.2.3",
    "less": "^2.7.1",
    "lodash": "^3.0.0",
    "magnific-popup": "^1.1.0",
    "node-sass": "^3.7.0",
    "progressbar.js": "^1.0.1",
    "react": "^15.0.1",
    "react-addons-css-transition-group": "^15.0.2",
    "react-color": "^2.2.2",
    "react-css": "0.0.2",
    "react-dom": "^15.0.1",
    "react-dragula": "^1.1.16",
    "react-dropzone": "^3.5.1",
    "react-redux": "^4.4.5",
    "react-router": "^2.3.0",
    "react-router-redux": "^4.0.4",
    "react-sidebar": "^2.1.2",
    "react-tabs": "^0.7.0",
    "react-validation-mixin": "^5.3.4",
    "reactcss": "^1.0.5",
    "redux": "^3.5.2",
    "redux-localstorage": "^0.4.1",
    "redux-thunk": "^2.1.0",
    "resolve-url-loader": "^1.4.3",
    "sass-loader": "^3.2.0"
  },
  "devDependencies": {
    "babel": "^6.5.2",
    "babel-core": "^6.7.7",
    "babel-loader": "^6.2.4",
    "babel-preset-es2015": "^6.6.0",
    "babel-preset-react": "^6.5.0",
    "babel-preset-react-hmre": "^1.1.1",
    "babel-preset-stage-0": "^6.5.0",
    "css-loader": "^0.23.1",
    "expect": "^1.20.1",
    "foundation-sites": "^6.2.1",
    "gulp": "^3.9.1",
    "gulp-compass": "^2.1.0",
    "gulp-if": "^2.0.1",
    "gulp-livereload": "^3.8.1",
    "gulp-serve": "^1.2.0",
    "gulp-util": "^3.0.7",
    "karma": "^0.13.22",
    "karma-chrome-launcher": "^1.0.1",
    "karma-mocha": "^1.0.1",
    "karma-mocha-reporter": "^2.0.3",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-webpack": "^1.7.0",
    "mocha": "^2.5.3",
    "react-addons-test-utils": "^15.1.0",
    "react-hot-loader": "^1.3.0",
    "redux-devtools": "^3.3.1",
    "resolve-url-loader": "^1.6.0",
    "script-loader": "^0.7.0",
    "source-map-loader": "^0.1.5",
    "style-loader": "^0.13.1",
    "url-loader": "^0.5.7",
    "webpack": "^1.13.0",
    "webpack-dev-middleware": "^1.6.1",
    "webpack-dev-server": "^1.14.1",
    "webpack-hot-middleware": "^2.10.0",
    "webpack-stream": "^3.2.0"
  }
}

**Comment by gwenf** [comment]
I figured out what it was.
I needed a loader for JSON. I guess because I normally have redux handling JSON so I don't have to include it directly in react components.

Anyway, [this fixed it](https://www.npmjs.com/package/json-loader):

```javascript
npm install json-loader --save
```

```javascript
{
        test: /\.json$/,
        loader: 'json'
}
````

**Comment by aknuds1** [comment]
I guess we can close this issue then :)
